### ISSUE TITLE
PDF file of schematic and pcb layout

### ISSUE THREAD

**Issue by karoria** [bdring/6-Pack_CNC_Controller#14]
Hi @bdring 
Can you share schematic and pcb layout of your latest 6 pack board? As I can't open files given. I use EasyEDA for pcb designing. I want to make some changes as per my machine and taste.

**Comment by KingMo5h** [comment]
Download Diptrace and try it out 30 days. Opne the file and then export as a file you want.

**Comment by bdring** [comment]
[Added](https://github.com/bdring/6-Pack_CNC_Controller/blob/master/versions/V1p1/Schematic%20-%206_Axis_I2S_v1p1.pdf)

**Comment by karoria** [comment]
Thanks a lot. :)
