### ISSUE TITLE
Just for fun....3 Pack 

### ISSUE THREAD

**Issue by bdring** [bdring/6-Pack_CNC_Controller#23]
I needed to test a new DC-DC power supply, so I decided to make a mini controller at the same time. 

This is tiny controller that uses CNC I/O Modules. It is about the size of an Arduino Uno. It has sockets for 3 axes and 3 modules. Other than the power supply, there is no active circuitry on the board. It took only about an hour to design. It shows how the modular concept allows you to quickly prototype a controller with professional level accessory support.

![20200814_131042](https://user-images.githubusercontent.com/189677/90313557-234dfa00-ded3-11ea-8934-b8f3b934769b.jpg)

![20200815_073919](https://user-images.githubusercontent.com/189677/90313558-277a1780-ded3-11ea-857a-c48db6e457f8.jpg)

**Comment by Skywalkerf34** [comment]
Nice design, as already said modular design helps a lot, then "just" route a new board and that's it !

**Comment by bdring** [comment]
It would be interesting to make a 5V DC-DC module.

It would use the VMot to output 5V using the module pins. That would further reduce the  complexity of the base controller.
