### ISSUE TITLE
New CNC I/O Module - Dynamixel Servos

### ISSUE THREAD

**Issue by bdring** [bdring/6-Pack_CNC_Controller#26]
This allows you to control Dynamixel servos. Dynamixel servos are on a bus, so you can connect a lot of them. I put two connectors, because you might have servos on either side of the controller. If your controller VMot is in the Dynamixel power range, you can use that. There is also an external connection to supply that voltage.

Here is a [video of a delta running these servos and Grbl_ESP32](https://www.youtube.com/watch?v=wPDP6ckP0sQ)

I also added a single RC Servo connector, because I had an extra I/O pin.

I'll probably wait to order this until I can join it with another order to save on shipping.

<img src="https://user-images.githubusercontent.com/189677/90946390-e19ce200-e3f1-11ea-8ea4-1aa1ef86c7cc.png" width="400">

<img src="https://user-images.githubusercontent.com/189677/90946527-4e64ac00-e3f3-11ea-9a87-ebae33be3d75.png" width="400">

**Comment by bdring** [comment]
Here is the module.

- It can pull servo power from VMot or use an external voltage (the switch).
- It has (2) Dynamixel Servo connectors. The servos are on a bus, so you really only need one, but this helps if servos are on either side of the controller.
- One normal RC Servo connector.  


Still testing right now.

<img src="https://user-images.githubusercontent.com/189677/92536018-387e2600-f1fe-11ea-9482-d682be36b951.jpg" width="400">

**Comment by bdring** [comment]
<img src="https://user-images.githubusercontent.com/189677/92671216-49e93000-f2db-11ea-8605-ee1b022e64ec.jpg" width="400">

<img src="https://user-images.githubusercontent.com/189677/92671229-5077a780-f2db-11ea-819d-fc63f6a1e0c4.jpg" width="400">

**Comment by Skywalkerf34** [comment]
Hi,
Can we use ESP32 GRBL to drive DELTA with this kind of smart servo? 
which parameter ? 
any machine def example?

**Comment by bdring** [comment]
There is a partially working example that will be complete within a week or two.  Please be patient.

Here it is running an older version of Grbl_ESP32.

https://www.youtube.com/watch?v=wPDP6ckP0sQ

I cannot provide any free support for using the delta. It is not part of the core Grbl_ESP32 project.

**Comment by Skywalkerf34** [comment]
Will wait for this example, thanks
