### ISSUE TITLE
Component Life Tracker

### ISSUE THREAD

**Issue by MCTaylor17** [bdring/6-Pack_CNC_Controller#34]
This might be a bit of a frivolous idea but I was thinking it might be valuable to track hardware component usage over it's lifetime. Something simple like a step counter or time based logging maybe?  The idea being it could give you a metric to look back at if something fails.

**Comment by bdring** [comment]
That is not easy to do. You never know when the controller will be shut off and we have limited write cycle memory for persistent values. This is a better question for the Grbl_ESP32 project, so I am closing it here.
