### ISSUE TITLE
Proximity Sensors beyond 5V

### ISSUE THREAD

**Issue by jsunday** [bdring/6-Pack_CNC_Controller#40]
What is involved in getting a 6-36V or 10-30V inductive proximity sensor to work correctly?

I have a 12V power supply I can use to power the sensor, and then I would need a resistor or other electronics of some type to lower the voltage for the input of the esp32?

Thanks,

**Comment by bdring** [comment]
Most proximity switches pull the signal to ground. I think if you supply the 12V to the sensor and tie the ground on sensor and the ground at the switch together it should work.

[Here is a link to Slack](https://join.slack.com/t/buildlog/shared_invite/zt-7twbithi-bRGScOaCgJoBpTbkykfxoA). The is the primary support channel for questions like this.
