### ISSUE TITLE
6 pack for MPCNC

### ISSUE THREAD

**Issue by jwslavinsky** [bdring/6-Pack_CNC_Controller#43]
Hi, I am converting over from Bart's MPCNC specific controller board to the six pack. 
I just want to verify before powering up, the 6 pack requires two power inputs, one green input terminal for the board labeled VMOT + and GND (12-24VDC), and a micro USB input to power up the ESP-32 (5VDC)?

**Comment by bdring** [comment]
It does not require the USB.
