### ISSUE TITLE
feadback sensor AS5600

### ISSUE THREAD

**Issue by sshahriyari** [bdring/6-Pack_CNC_Controller#55]
Hi, I used AS5600 sensor as encoder on my machine.
how can I use data comes from sensor?

for Monitoring, Data Logging, ....

**Comment by sshahriyari** [comment]
helloooo....

is this even possible ?!

**Comment by bdring** [comment]
Encoders are not supported

**Comment by bdring** [comment]
We have a Discord server for FluidNC if you want to discuss further.

https://discord.gg/nxZFVNKd
