### ISSUE TITLE
No Source file for 0-10V spindle

### ISSUE THREAD

**Issue by abrackers** [bdring/6-Pack_CNC_Controller#63]
Thanks for all of your work on this. I noticed there was no Source file available for the 0-10v spindle module, while all of the other modules had diptrace (or in one case kicad) source files. Would it be possilble for you to provide the source file for the 0-10v spindle module? Thanks

**Comment by bdring** [comment]
Here is the most current version.

https://oshwlab.com/bdring/10v-spindle-cnc-i-o-module

**Comment by abrackers** [comment]
Thanks, I hadn't found that site yet
