### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by Mamoonpk** [bdring/6-Pack_CNC_Controller#66]
Hi, I have to ask I am pretty new to CNCs. 

I have been using fusion 360 for most of my CNC designing and using 6 pack cnc controller running with fluidnc

Can I use Easel pro or Carbide to generate gcode, and is it compatible?

**Comment by bdring** [comment]
Yes, we are compatible with Grbl gcode.

**Comment by Mamoonpk** [comment]
Thanks - I made 3d relief successfully on Easel pro.
