### ISSUE TITLE
Modules to test.

### ISSUE THREAD

**Issue by bdring** [bdring/6-Pack_CNC_Controller#7]
I got a bunch of spindle modules to test.

![image](https://user-images.githubusercontent.com/189677/84600377-6392ec80-ae3e-11ea-8186-ce88ad2e1e02.png)

The relay one is tested and installed.

![image](https://user-images.githubusercontent.com/189677/84600371-51b14980-ae3e-11ea-8fdc-f8fd6832853d.png)

Testing soon. RS485 modbus, 0-10V and 5V PWM.

**Comment by Bleeptech** [comment]
Nice! I've been looking for a controller for an XXYZZ build with DM542A external drivers and this looks very promising..
A set of jumpers across the driver sockets should be enough to expose the signals I need.. 
Is there a machine file for this or have I not dug deeply enough into the code?

Bleeptech

P.S. Any chance you'd sell me a partially populated board and a set of the screw connectors?
[ I could breadboard it but they always end up looking like an LA freeway map.. LOL ]

**Comment by bdring** [comment]
The latest version is on order. If it checks out I will be selling fully assembled versions.

There is a PCB version of the jumper you are talking about. The jumper just allows you to choose between a common ground or common 5V.

![image](https://user-images.githubusercontent.com/189677/85921798-6d581f00-b844-11ea-9548-f937870b76ab.png)

**Comment by bdring** [comment]
![20200711_131716](https://user-images.githubusercontent.com/189677/93836299-ee5a6300-fc47-11ea-8398-9aaca2ea094e.jpg)

**Comment by bdring** [comment]
![20200711_132713](https://user-images.githubusercontent.com/189677/93836374-2d88b400-fc48-11ea-8ecd-c18c63e64a02.jpg)
